name: "fastapi-app_2401-filebeat"
logging.metrics.enabled: false
xpack.security.enabled: false
xpack.monitoring.enabled: false
setup.ilm.enabled: false
setup.template.enabled: false

filebeat.inputs:
  - type: log
    scan_frequency: 1s
    enabled: true
    path:
      - src/logs/fastapi*
    fields:
      - service: app_2401
    fields_under_root: true

output.elasticsearch:
  hosts: ["elastic_2401:9203"]
  index: "fastapi-app_2401"
