version: "3.0"
services:
  db_5:
    container_name: db_5
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432

networks:
  default:
    name: nginx_proxy
    external: true
