version: "3.0"
services:
  app_2401:
    build: ./src
    container_name: app_2401
    environment:
      SENTRY_URL: "https://e94f707391cbbc8c1e27d0c3391c0564@o4505918059118592.ingest.sentry.io/4506592294797312"
      APP_PORT: "8000"
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    env_file:
      - .env
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

  celery_2401:
    build: ./src
    container_name: celery_2401
    volumes:
      - ./src:/src
    env_file:
      - .env
    command: celery -A tasks.tasks:celery_app worker --loglevel=INFO

  flower_2401:
    image: mher/flower
    container_name: flower_2401
    ports:
      - "5555:5555"
    volumes:
      - ./wait_flw.sh:/wait_flw.sh
    command: ['/wait_flw.sh']

  prometheus_2401:
    image: prom/prometheus:v2.43.0
    container_name: prometheus_2401
    volumes:
      - ./prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data_2401:/prometheus
    depends_on:
      - app_2401
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"

  grafana_2401:
    image: grafana/grafana:8.5.22
    container_name: grafana_2401
    volumes:
      - grafana-data_2401:/var/lib/grafana
      - grafana-config_2401:/etc/grafana
    depends_on:
      - prometheus_2401
    restart: always
    ports:
      - "3000:3000"
    user: "0"

networks:
  default:
    name: nginx_proxy
    driver: bridge
    external: true

volumes:
  grafana-data_2401:
  grafana-config_2401:
  prometheus-data_2401:
#  redis-data_2401:
