version: "3.0"
services:
  app_2401:
    build: ./src
    container_name: app_2401
    restart: always
    ports:
      - ${APP_PORT}:8000
    volumes:
      - ./src:/src
    env_file:
      - .env
    command: uvicorn main:app --reload --host 0.0.0.0 --port ${APP_PORT}

  celery_2401:
    build: ./src
    container_name: celery_2401
    restart: always
    volumes:
      - ./src:/src
    env_file:
      - .env
    command: celery -A tasks.tasks:celery_app worker --loglevel=INFO

  flower_2401:
    image: mher/flower
    container_name: flower_2401
    restart: always
    ports:
      - ${FLW_PORT}:5555
    volumes:
      - ./wait_flw.sh:/wait_flw.sh
    depends_on:
      - app_2401
      - celery_2401
    command: ['/wait_flw.sh']

  prometheus_2401:
    image: prom/prometheus:v2.43.0
    container_name: prometheus_2401
    restart: always
    volumes:
      - ./prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data_2401:/prometheus
    depends_on:
      - app_2401
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - ${PRTH_PORT}:9090

  grafana_2401:
    image: grafana/grafana:8.5.22
    container_name: grafana_2401
    restart: always
    volumes:
      - grafana-data_2401:/var/lib/grafana
      - grafana-config_2401:/etc/grafana
    depends_on:
      - prometheus_2401
    ports:
      - ${GRF_PORT}:3000
    user: "0"

  jaeger_2401:
    image: jaegertracing/all-in-one:1.48
    container_name: jaeger_2401
    restart: always
    ports:
      - ${JEAGER_PORT_UDP}:6831
      - ${JEAGER_PORT_TCP}:16686
    depends_on:
      - app_2401

networks:
  default:
    name: nginx_proxy
    driver: bridge
    external: true

volumes:
  grafana-data_2401:
  grafana-config_2401:
  prometheus-data_2401:
