"""test running migrations

Revision ID: 034118a33866
Revises: 2ca75de2d70f
Create Date: 2024-01-09 18:18:39.522878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034118a33866'
down_revision = '2ca75de2d70f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
