"""test running migrations

Revision ID: 2024d6a77290
Revises: fc5cf6ae2db3
Create Date: 2024-01-09 19:04:06.255677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2024d6a77290'
down_revision = 'fc5cf6ae2db3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
