"""test running migrations

Revision ID: 2ca75de2d70f
Revises: d56cf218a1dc
Create Date: 2024-01-09 18:10:18.542478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ca75de2d70f'
down_revision = 'd56cf218a1dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
