"""test running migrations

Revision ID: 4c11612e2db2
Revises: 73bb581102ab
Create Date: 2024-01-09 19:56:23.409525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c11612e2db2'
down_revision = '73bb581102ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
