"""test running migrations

Revision ID: 579031bf1d67
Revises: 4c11612e2db2
Create Date: 2024-01-09 19:58:59.582032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '579031bf1d67'
down_revision = '4c11612e2db2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
