"""test running migrations

Revision ID: 633fa95007be
Revises: 7a1b938d65ff
Create Date: 2024-01-09 18:52:42.520847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '633fa95007be'
down_revision = '7a1b938d65ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
