"""test running migrations

Revision ID: 73bb581102ab
Revises: a0f9ef26157b
Create Date: 2024-01-09 19:05:29.207550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73bb581102ab'
down_revision = 'a0f9ef26157b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
