"""test running migrations

Revision ID: 7a1b938d65ff
Revises: 8f31e019b8f6
Create Date: 2024-01-09 18:49:35.517143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a1b938d65ff'
down_revision = '8f31e019b8f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
