"""test running migrations

Revision ID: 8f31e019b8f6
Revises: 034118a33866
Create Date: 2024-01-09 18:24:01.886586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f31e019b8f6'
down_revision = '034118a33866'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
