"""test running migrations

Revision ID: a0f9ef26157b
Revises: 2024d6a77290
Create Date: 2024-01-09 19:04:48.346790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0f9ef26157b'
down_revision = '2024d6a77290'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
