"""test running migrations

Revision ID: b4de7960eb75
Revises: 633fa95007be
Create Date: 2024-01-09 19:00:25.914917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4de7960eb75'
down_revision = '633fa95007be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
