"""test running migrations

Revision ID: d3d2ad937085
Revises: 579031bf1d67
Create Date: 2024-01-10 12:39:57.600102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3d2ad937085'
down_revision = '579031bf1d67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
