"""test running migrations

Revision ID: fc5cf6ae2db3
Revises: b4de7960eb75
Create Date: 2024-01-09 19:02:15.046562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc5cf6ae2db3'
down_revision = 'b4de7960eb75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
