"""test running migrations

Revision ID: c761d232e1fa
Revises: b958ec42f84e
Create Date: 2024-01-10 12:40:24.552682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c761d232e1fa'
down_revision = 'b958ec42f84e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
